const LOG_FILE_NAME = 'log.txt';
const DEFAULT_SITEMAP_URL = 'https://frankmtaylor.com/sitemap.xml';
const DEFAULT_SHOULD_CRAWL_SITEMAP = false;
const DEFAULT_OUTPUT_FILE = 'pages.json';
const DEFAULT_SELECTOR = '.title';
const DEFAULT_IS_SPA = false;
const DEFAULT_LIMIT = 0;
const DEFAULT_TAKE_SCREENSHOTS = false;
const DEFAULT_SHOW_ELEMENT_DETAILS = false;
const DEFAULT_SHOW_HTML = true;
const DEFAULT_CRAWL = false;

module.exports = {
  LOG_FILE_NAME,
  DEFAULT_SITEMAP_URL,
  DEFAULT_SHOULD_CRAWL_SITEMAP,
  DEFAULT_SELECTOR,
  DEFAULT_OUTPUT_FILE,
  DEFAULT_IS_SPA,
  DEFAULT_LIMIT,
  DEFAULT_TAKE_SCREENSHOTS,
  DEFAULT_SHOW_ELEMENT_DETAILS,
  DEFAULT_SHOW_HTML,
  DEFAULT_CRAWL,
};
