name: CI
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run 'lint' task
        run: npm run lint

      - name: Run 'test' task
        run: npm run test
